# services/auth-svc/Dockerfile.dev

FROM golang:1.24-alpine

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY gen/go/logistics/auth/ ./gen/go/logistics/auth/
COPY gen/go/logistics/common/ ./gen/go/logistics/common/
COPY gen/openapi/ ./gen/openapi/

COPY pkg/apperror/ ./pkg/apperror/
COPY pkg/audit/ ./pkg/audit/
COPY pkg/config/ ./pkg/config/
COPY pkg/database/ ./pkg/database/
COPY pkg/interceptors/ ./pkg/interceptors/
COPY pkg/logger/ ./pkg/logger/
COPY pkg/metrics/ ./pkg/metrics/
COPY pkg/passhash/ ./pkg/passhash/
COPY pkg/ratelimit/ ./pkg/ratelimit/
COPY pkg/server/ ./pkg/server/
COPY pkg/swagger/ ./pkg/swagger/
COPY pkg/telemetry/ ./pkg/telemetry/

COPY services/auth-svc/ ./services/auth-svc/
COPY migrations/ ./migrations/

EXPOSE 50055 8055

CMD ["air", "-c", "services/auth-svc/.air.toml"]
